language: python

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      python: 2.7
    - os: linux
      dist: xenial
      sudo: required
      python: 2.7

addons:
  apt:
    update: true
    packages:
      - python-pip

before_install:
  - sudo apt-get -qq update

install:
  - sudo pip install ansible
  - ansible --version 
  - cat /etc/*-release

script:
  - ansible-playbook playbooks/main.yml
