dist: xenial

addons:
  apt:
    update: true

before_install:
  - sudo apt-get -qq update
  - sudo apt-get -y install git python3 python3-pip ansible

script:
  - ansible-playbook playbooks/main.yml -i hosts --sudo
