dist: xenial

addons:
  apt:
    update: true
    packages:
      - python-pip

before_install:
  - sudo apt-get -qq update

install:
  - pip install ansible

script:
  - ansible --version
  - ansible-playbook playbooks/main.yml
