dist: xenial
language: python
python: "3.4"

# addons:
#   apt:
#     update: true

before_install:
  - sudo apt-get -qq update

install:
  - pip install ansible

script:
  - ansible-playbook playbooks/main.yml -i hosts --sudo
