dist: xenial

addons:
  apt:
    update: true

before_install:
  - sudo apt-get -qq update

install:
  - sudo apt-get -y install python3 python3-pip
  - sudo apt-get -y install ansible

script:
  - ansible --version
  - ansible-playbook playbooks/main.yml
