---
# Install & Configure Vagrant
# https://vagrant-deb.linestarve.com/

- name: Add vagrant repository
  apt_repository: repo="{{ vagrant_ppa }}" state=present

- name: Add public key
  apt_key: keyserver="{{ vagrant_ppa_keyserver }}" id="{{ vagrant_ppa_id }}" state=present

- name: Update package manager
  apt: update_cache=yes

- name: Install latest vagrant package
  apt: pkg="{{ item }}" state=latest
  with_items:
    - vagrant
