---
# Install & Configure NodeJS

- name: Add node repository
  apt_repository: repo="{{ node_ppa }}" state=present
  sudo: true

- name: Add public key
  apt_key: url="{{ node_ppa_key }}" state=present
  sudo: true

- name: Update package manager
  apt: update_cache=yes
  sudo: true

- name: Install latest node package
  apt: pkg="{{ item }}" state=latest
  with_items:
    - nodejs
  sudo: true

# Install Node Packages

- include_tasks: npm.yml