---
# Install & Configure NodeJS

- name: Check if nodejs is installed
  command: dpkg-query -W nodejs
  register: node_check_pkg
  failed_when: node_check_pkg.rc > 1
  changed_when: node_check_pkg.rc == 1

- include: repository.yml
  when: node_check_pkg.rc == 1

- include: install.yml
  when: node_check_pkg.rc == 1

- include: npm.yml