---
# Install & Configure NodeJS

- name: Add node repository
  apt_repository: repo="{{ node_ppa }}" state=present

- name: Add public key
  apt_key: url="{{ node_ppa_key }}" state=present

- name: Update package manager
  apt: update_cache=yes

- name: Install latest node package
  apt: pkg="{{ item }}" state=latest
  with_items:
    - nodejs

# Install Node Packages

- include_task: npm.yml