---
# Add NodeJS Repository

- name: Download node setup script
  get_url: 
    url="{{ nodejs_setup_url }}"
    dest="/home/{{ ansible_env.USER }}/Downloads/node_setup.sh"

- name: Make node setup script executable
  file: 
    path="/home/{{ ansible_env.USER }}/Downloads/node_setup.sh"
    state=touch
    mode="u+x"

- name: Execute the node setup script
  command: "/home/{{ ansible_env.USER }}/Downloads/node_setup.sh"
  sudo: true

- name: Update package manager
  apt: update_cache=yes
  sudo: true