---
# Install & Configure Spotify

- name: Add spotify repository
  apt_repository: repo="{{ spotify_ppa }}" state=present

- name: Add public key
  apt_key: keyserver="{{ spotify_ppa_keyserver }}" id="{{ spotify_ppa_id }}" state=present

- name: Update package manager
  apt: update_cache=yes

- name: Install latest spotify package
  apt: pkg="{{ item }}" state=latest force=yes
  with_items:
    - spotify-client
