---
# Install & Configure Common Tools

- name: Install common tools
  apt: pkg="{{ item }}" state=present force=yes
  with_items:
    - curl
    - gcc
    - make
    - nmap
    - wget
    - build-essential
    - apt-transport-https
    - ca-certificates
    - software-properties-common
