---
# Install & Configure Skype
# SkypeForLinux - Wrapper around Skype web client

- name: Add skype repository
  apt_repository: repo="{{ skype_ppa }}" state=present

- name: Add public key
  apt_key: url="{{ skype_ppa_key }}" state=present

- name: Update package manager
  apt: update_cache=yes

- name: Install latest skype package
  apt: pkg="{{ item }}" state=latest force=yes
  with_items:
    - skypeforlinux
